version: '3'

services:
    redis:
        image: redis
        container_name: redisserver
        ports: ["6379:6379"]
        restart: always
        network_mode: host
    backend:
        network_mode: host
        build:
            context: ./backend
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - redis
    frontend: 
        ports:
            - "8080:8080"
        build:
            context: ./frontend
            dockerfile: Dockerfile
        restart: always
        network_mode: host
        depends_on:
            - backend