name: workflow
on: push
env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
jobs:
  docker:
    runs-on: ubuntu-latest
  steps:
  - name: Git Checkout
    uses: actions/checkout@v2
  - name: Docker compose start
    run: docker-compose build && docker-compose up
    timeout-minutes: 4
